#!/usr/bin/env bash
#
# ZooLink — canonical `.env` provisioner (the ONE documented env path; ADR-0009 compose topology).
#
# WHY THIS EXISTS
#   The old documented path was `cp .env.example .env`. `.env.example` is a FORM (a commented
#   inventory of every key with placeholder values), not a provisioner: copying it verbatim yields
#   `METRICS_TOKEN=` (empty) and `__change_me__` secrets, so a NODE_ENV=production boot dies in
#   backend/src/config/env.validation.ts (`METRICS_TOKEN: required in production`). Two documented
#   paths (a form pretending to be a provisioner, and hand-editing) is exactly the drift this
#   script removes: `.env.example` stays the FORM, this script is the PATH.
#
# CONTRACT (deterministic; no interactive prompts, no guessing)
#   * `.env` ABSENT                → create it in full. Every secret is MINTED with `openssl rand
#                                    -hex` at lengths >= what env.validation.ts requires. chmod 600.
#   * `.env` PRESENT (default)     → the file is NOT touched AT ALL. Print the NAMES of the missing
#                                    prod-required keys and exit 1; exit 0 (zero changes) if none.
#   * `--fill-missing`             → mint/fill ONLY the keys that are absent or present-but-empty.
#                                    An existing NON-EMPTY value is NEVER re-minted or reformatted.
#                                    Idempotent: a second run on a complete file changes nothing.
#
#   "Missing" == absent OR present-with-an-empty-value, because the validator treats an empty
#   string as "not set" (see the METRICS_TOKEN / AGENT_SERVICE_SIGNING_SECRET blocks in
#   env.validation.ts). That is what makes `cp .env.example .env` visibly incomplete here.
#
# OUTPUT DISCIPLINE
#   This script NEVER prints a secret (or any value) to stdout/stderr — only KEY NAMES. The only
#   place values exist is the 0600 `.env` it writes.
#
# USAGE
#   deploy/gen-env.sh                              # check mode (default) — never writes
#   deploy/gen-env.sh --domain zoolink.ru          # create (only if .env is absent)
#   deploy/gen-env.sh --fill-missing               # top up an existing .env
#   deploy/gen-env.sh --env-file /path/to/.env     # operate on a non-default path (CI/tests)
#   deploy/gen-env.sh --node-env development       # default: production
#
set -euo pipefail

PROG="gen-env.sh"

die() {
  printf '%s: error: %s\n' "$PROG" "$*" >&2
  exit 2
}

note() { printf '%s: %s\n' "$PROG" "$*"; }

# --------------------------------------------------------------------------------------------- #
# Arguments
# --------------------------------------------------------------------------------------------- #
ENV_FILE=".env"
DOMAIN="localhost"
NODE_ENV_VALUE="production"
MODE="check" # check | create (implied when the file is absent) | fill

usage() {
  cat <<'USAGE'
Usage: deploy/gen-env.sh [--domain HOST] [--node-env ENV] [--fill-missing] [--env-file PATH]

  --domain HOST      PUBLIC_DOMAIN to write (default: localhost). Non-secret.
  --node-env ENV     NODE_ENV to write: development|test|production (default: production).
  --fill-missing     Top up an EXISTING .env: mint/fill only absent-or-empty keys.
  --env-file PATH    Target file (default: ./.env).
  -h, --help         This text.

Exit codes: 0 = ok / nothing to do · 1 = prod-required keys missing (check mode) · 2 = usage or
environment error.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --domain)
      [ $# -ge 2 ] || die "--domain requires a value"
      DOMAIN="$2"
      shift 2
      ;;
    --node-env)
      [ $# -ge 2 ] || die "--node-env requires a value"
      case "$2" in
        development | test | production) NODE_ENV_VALUE="$2" ;;
        *) die "--node-env must be one of: development, test, production" ;;
      esac
      shift 2
      ;;
    --env-file)
      [ $# -ge 2 ] || die "--env-file requires a value"
      ENV_FILE="$2"
      shift 2
      ;;
    --fill-missing)
      MODE="fill"
      shift
      ;;
    --check)
      MODE="check"
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
done

command -v openssl >/dev/null 2>&1 || die "openssl not found — required to mint secrets"

# --------------------------------------------------------------------------------------------- #
# Key registry
#
# LAYOUT is the SINGLE source of both the rendered file and the key list: an entry starting with
# '@' is a key, anything else is emitted verbatim (section comments / blank lines). Keeping one
# list means the renderer and the checker can never drift apart.
# --------------------------------------------------------------------------------------------- #
LAYOUT=(
  "# ZooLink environment — GENERATED by deploy/gen-env.sh. Secrets are randomly minted; keep mode 0600."
  "# NEVER commit this file (.gitignore). The commented inventory of every key lives in .env.example (the FORM)."
  "# Shape is validated at boot by backend/src/config/env.validation.ts (fail-fast)."
  ""
  "# ---- App ----"
  "@NODE_ENV"
  "@PORT"
  "@PUBLIC_DOMAIN"
  "@ENABLE_DEV_TOKEN"
  "@CORS_ORIGINS"
  ""
  "# ---- PostgreSQL (internal network only — never published to the host) ----"
  "@POSTGRES_USER"
  "@POSTGRES_PASSWORD"
  "@POSTGRES_DB"
  "@DATABASE_URL"
  ""
  "# ---- Redis ----"
  "@REDIS_PASSWORD"
  "@REDIS_URL"
  ""
  "# ---- Object storage (MinIO self-host default; Yandex Object Storage in prod — ADR-0008) ----"
  "# RF data residency (ADR-0017 п.4 / ФЗ-152 ст.18 ч.5): the bucket holds PII (provider documents,"
  "# avatars, listing photos), so the S3_ENDPOINT HOST must be self-hosted (http://minio:9000 /"
  "# localhost / a private address) or an approved RF store — an RF domain (.ru/.su/.рф) or"
  "# https://storage.yandexcloud.net. A foreign bucket (s3.amazonaws.com, *.backblazeb2.com) is"
  "# refused at boot and by scripts/check-rf-residency.sh. Pinning S3_REGION below does NOT make a"
  "# foreign endpoint lawful: the region string and the host are independent checks."
  "@S3_ENDPOINT"
  "@S3_ACCESS_KEY"
  "@S3_SECRET_KEY"
  "@S3_BUCKET"
  "# MEDIA_CDN_HOST is ADDED to the media-URL allowlist, so a foreign CDN would cache and serve"
  "# avatars (PII, ADR-0012) outside the RF — non-RF CDNs are boot-blocking. Bare host[:port], no"
  "# scheme. EMPTY = no CDN (the default, media served straight from the S3 origin)."
  "@MEDIA_CDN_HOST"
  "# RF data residency (ADR-0017 / ФЗ-152 ст.18 ч.5): every *_REGION must be an approved RF id."
  "@S3_REGION"
  "@RESIDENCY_ALLOW_NON_RF_DEV"
  ""
  "# ---- Auth / JWT / PII crypto (ADR-0001, ADR-0019) ----"
  "@JWT_ACCESS_SECRET"
  "@JWT_REFRESH_SECRET"
  "@JWT_ACCESS_TTL"
  "@JWT_REFRESH_TTL"
  "@PHONE_HASH_PEPPER"
  "@PII_DATA_KEY"
  "@PII_BLIND_INDEX_KEY"
  "@AGENT_SERVICE_SIGNING_SECRET"
  ""
  "# ---- SMS (SMS.RU — ADR-0008). Empty credential = stub mode. ----"
  "@SMS_PROVIDER"
  "@SMSRU_API_ID"
  "@SMS_FROM"
  ""
  "# ---- Email (Unisender — ADR-0008). Empty credential = stub mode. ----"
  "@EMAIL_PROVIDER"
  "@UNISENDER_API_KEY"
  "@UNISENDER_LIST_ID"
  "@EMAIL_FROM"
  "@EMAIL_FROM_NAME"
  ""
  "# ---- Maps (Yandex.Maps — ADR-0008) ----"
  "@YANDEX_MAPS_API_KEY"
  ""
  "# ---- OAuth (all empty = provider off; Apple is all-or-nothing in production) ----"
  "@OAUTH_GOOGLE_CLIENT_ID"
  "@OAUTH_GOOGLE_CLIENT_SECRET"
  "@OAUTH_APPLE_CLIENT_ID"
  "@OAUTH_APPLE_TEAM_ID"
  "@OAUTH_APPLE_KEY_ID"
  "@OAUTH_APPLE_PRIVATE_KEY"
  "@OAUTH_TELEGRAM_BOT_TOKEN"
  "@OAUTH_VK_CLIENT_ID"
  "@OAUTH_VK_CLIENT_SECRET"
  ""
  "# ---- Retention job (worker-only) ----"
  "@RETENTION_TICK_CRON"
  "@RETENTION_GRACE_DAYS"
  ""
  "# ---- Abuse limits ----"
  "@LISTING_CREATION_QUOTA_PER_DAY"
  ""
  "# ---- Payments (Фаза 2+, gated by feature_toggles.payments) ----"
  "@PAYMENT_PROVIDER"
  "@YOOKASSA_SHOP_ID"
  "@YOOKASSA_SECRET_KEY"
  ""
  "# ---- Observability ----"
  "# METRICS_TOKEN is REQUIRED in production (>=16): without it MetricsGuard falls back to trusting"
  "# req.ip, and behind Caddy every client looks internal — /metrics would be world-readable."
  "@METRICS_TOKEN"
  "# SENTRY_DSN empty = error reporting off (default). If set, the ingest HOST must be self-hosted"
  "# (localhost/private/compose service name) or an RF domain (.ru/.su) — ADR-0017 п.6 / ФЗ-152"
  "# ст.18 ч.5: stack traces carry PII. A foreign ingest (*.ingest.sentry.io) is refused at boot."
  "@SENTRY_DSN"
  "@LOG_LEVEL"
)

# Secrets: key -> number of random BYTES for `openssl rand -hex` (hex output is 2x that many chars).
# Lengths are chosen to clear the validator minimums with margin (JWT/pepper/PII >=32 chars ->
# 32 bytes = 64 chars; METRICS_TOKEN >=16 chars -> 16 bytes = 32 chars).
declare -A SECRET_BYTES=(
  [POSTGRES_PASSWORD]=16
  [REDIS_PASSWORD]=16
  [S3_ACCESS_KEY]=10
  [S3_SECRET_KEY]=20
  [JWT_ACCESS_SECRET]=32
  [JWT_REFRESH_SECRET]=32
  [PHONE_HASH_PEPPER]=32
  [PII_DATA_KEY]=32
  [PII_BLIND_INDEX_KEY]=32
  [AGENT_SERVICE_SIGNING_SECRET]=32
  [METRICS_TOKEN]=16
)

# Non-secret defaults. Keys absent from BOTH this map and SECRET_BYTES default to the empty string
# (intentionally: optional provider credentials / OAuth ids the operator fills in later).
declare -A DEFAULTS=(
  [PORT]=3000
  [ENABLE_DEV_TOKEN]=false
  [POSTGRES_USER]=zoolink
  [POSTGRES_DB]=zoolink
  [S3_ENDPOINT]=http://minio:9000
  [S3_BUCKET]=zoolink-media
  [S3_REGION]=ru-central1
  [RESIDENCY_ALLOW_NON_RF_DEV]=false
  [JWT_ACCESS_TTL]=15m
  [JWT_REFRESH_TTL]=7d
  [SMS_PROVIDER]=smsru
  [EMAIL_PROVIDER]=unisender
  [EMAIL_FROM_NAME]=ZooLink
  [RETENTION_TICK_CRON]="0 * * * *"
  [RETENTION_GRACE_DAYS]=30
  [LISTING_CREATION_QUOTA_PER_DAY]=20
  [PAYMENT_PROVIDER]=yookassa
  [LOG_LEVEL]=info
)

# Prod-required = (a) every key the boot validator refuses to start without in production, and
# (b) every key docker-compose.yml interpolates (an unset one silently becomes "" and breaks the
# service). (a) MIRRORS backend/src/config/env.validation.ts — the lock against drift is the unit
# test src/config/gen-env.spec.ts, which DERIVES the required set from the real zod schema and
# asserts this generator emits all of it.
REQUIRED_KEYS=(
  # (a) env.validation.ts: no .default() in envSchema, plus the production-only refines
  DATABASE_URL
  REDIS_URL
  S3_ENDPOINT
  S3_ACCESS_KEY
  S3_SECRET_KEY
  S3_BUCKET
  JWT_ACCESS_SECRET
  JWT_REFRESH_SECRET
  PHONE_HASH_PEPPER
  PII_DATA_KEY
  PII_BLIND_INDEX_KEY
  AGENT_SERVICE_SIGNING_SECRET
  METRICS_TOKEN
  # (b) docker-compose.yml ${...} interpolation
  PUBLIC_DOMAIN
  POSTGRES_USER
  POSTGRES_PASSWORD
  POSTGRES_DB
  REDIS_PASSWORD
)

# --------------------------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------------------------- #
declare -A VAL=()   # final value per key
declare -A HELD=()  # keys whose value came from the EXISTING file (never re-minted)

mint() { openssl rand -hex "$1"; }

# Read `KEY=VALUE` lines from an existing env file into VAL/HELD. Comments, blank lines and lines
# without '=' are ignored. Only NON-EMPTY values are held: an empty value means "not set" (same
# reading as the validator), so it stays eligible for filling.
load_existing() {
  local file="$1" line key value
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      '#'* | '') continue ;;
    esac
    case "$line" in
      *=*) ;;
      *) continue ;;
    esac
    key="${line%%=*}"
    value="${line#*=}"
    # Reject anything that is not a plain shell-style identifier (defensive; keeps the parser and
    # docker-compose's env_file reader in agreement).
    case "$key" in
      [A-Za-z_]*)
        [ -z "${key//[A-Za-z0-9_]/}" ] || continue
        ;;
      *) continue ;;
    esac
    if [ -n "$value" ]; then
      VAL["$key"]="$value"
      HELD["$key"]=1
    fi
  done <"$file"
}

# Fill every key in LAYOUT that has no value yet: mint if secret, else use the default, else "".
resolve_values() {
  local entry key
  for entry in "${LAYOUT[@]}"; do
    case "$entry" in
      '@'*) key="${entry#@}" ;;
      *) continue ;;
    esac
    [ -n "${VAL[$key]+set}" ] && continue
    if [ -n "${SECRET_BYTES[$key]+set}" ]; then
      VAL["$key"]="$(mint "${SECRET_BYTES[$key]}")"
    elif [ -n "${DEFAULTS[$key]+set}" ]; then
      VAL["$key"]="${DEFAULTS[$key]}"
    else
      VAL["$key"]=""
    fi
  done
  # Argument-driven, non-secret.
  [ -n "${HELD[NODE_ENV]+set}" ] || VAL[NODE_ENV]="$NODE_ENV_VALUE"
  [ -n "${HELD[PUBLIC_DOMAIN]+set}" ] || VAL[PUBLIC_DOMAIN]="$DOMAIN"
  # Derived AFTER the credentials above, so a held POSTGRES_PASSWORD is reused rather than a fresh
  # mint leaking into a connection string that no longer matches the database.
  #
  # RF RESIDENCY (ADR-0017 п.1, ФЗ-152 ст.18 ч.5): the hosts below are deliberately the COMPOSE SERVICE
  # NAMES `postgres` / `redis` — i.e. self-hosted, inside our own network. DATABASE_URL is the PRIMARY
  # store of personal data and REDIS_URL holds the counters/cached payloads derived from it, so both must
  # stay self-hosted (service name / localhost / private address / unix socket) or move under an RF domain
  # (.ru/.su/.рф). A managed FOREIGN endpoint (Neon, AWS RDS, Supabase, Upstash, Redis Cloud …) is
  # FORBIDDEN. If you HOLD an existing value (the `HELD[...]` branch above preserves whatever is already
  # in `.env`), that held value is NOT exempt: the boot validator rejects it and
  # `scripts/check-rf-residency.sh` fails. This generator does not enforce residency itself — it only
  # never introduces a violation; enforcement is layer 1 (boot) + layer 2 (the CI gate).
  [ -n "${HELD[DATABASE_URL]+set}" ] ||
    VAL[DATABASE_URL]="postgresql://${VAL[POSTGRES_USER]}:${VAL[POSTGRES_PASSWORD]}@postgres:5432/${VAL[POSTGRES_DB]}?schema=public"
  [ -n "${HELD[REDIS_URL]+set}" ] ||
    VAL[REDIS_URL]="redis://:${VAL[REDIS_PASSWORD]}@redis:6379"
  [ -n "${HELD[EMAIL_FROM]+set}" ] || VAL[EMAIL_FROM]="noreply@${VAL[PUBLIC_DOMAIN]}"
}

# Names (never values) of prod-required keys with no non-empty value.
missing_required() {
  local key
  for key in "${REQUIRED_KEYS[@]}"; do
    if [ -z "${VAL[$key]+set}" ] || [ -z "${VAL[$key]}" ]; then
      printf '%s\n' "$key"
    fi
  done
}

# Write the whole file from LAYOUT, 0600, atomically (temp + mv in the same directory).
render_to() {
  local target="$1" dir tmp entry key
  dir="$(dirname -- "$target")"
  tmp="$(mktemp "$dir/.env.gen.XXXXXX")"
  chmod 600 "$tmp"
  for entry in "${LAYOUT[@]}"; do
    case "$entry" in
      '@'*)
        key="${entry#@}"
        printf '%s=%s\n' "$key" "${VAL[$key]}"
        ;;
      *) printf '%s\n' "$entry" ;;
    esac
  done >"$tmp"
  mv -- "$tmp" "$target"
  chmod 600 "$target"
}

# Rewrite an existing file in place, changing ONLY empty-valued lines whose key is being filled,
# then append the keys that were absent entirely. Every other byte is passed through untouched.
fill_into() {
  local target="$1" dir tmp line key
  shift
  local -A fill_set=()
  local k
  for k in "$@"; do fill_set["$k"]=1; done

  dir="$(dirname -- "$target")"
  tmp="$(mktemp "$dir/.env.gen.XXXXXX")"
  chmod 600 "$tmp"

  local -A seen=()
  while IFS= read -r line || [ -n "$line" ]; do
    key=""
    case "$line" in
      '#'* | '') ;;
      *=*)
        key="${line%%=*}"
        [ -z "${key//[A-Za-z0-9_]/}" ] || key=""
        ;;
    esac
    if [ -n "$key" ] && [ -n "${fill_set[$key]+set}" ] && [ -z "${line#*=}" ]; then
      printf '%s=%s\n' "$key" "${VAL[$key]}"
      seen["$key"]=1
    else
      printf '%s\n' "$line"
      if [ -n "$key" ]; then seen["$key"]=1; fi
    fi
  done <"$target" >"$tmp"

  local appended=0
  for k in "$@"; do
    [ -n "${seen[$k]+set}" ] && continue
    if [ "$appended" -eq 0 ]; then
      printf '\n# ---- added by %s (%s) ----\n' "$PROG" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >>"$tmp"
      appended=1
    fi
    printf '%s=%s\n' "$k" "${VAL[$k]}" >>"$tmp"
  done

  mv -- "$tmp" "$target"
  chmod 600 "$target"
}

# --------------------------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------------------------- #
if [ ! -e "$ENV_FILE" ]; then
  # ---- CREATE ----------------------------------------------------------------------------- #
  resolve_values
  still_missing="$(missing_required || true)"
  [ -z "$still_missing" ] || die "internal: generator did not emit required key(s): $still_missing"
  render_to "$ENV_FILE"
  note "created $ENV_FILE (mode 0600) — secrets minted with 'openssl rand -hex'."
  note "minted secret keys (names only): ${!SECRET_BYTES[*]}"
  note "NODE_ENV / PUBLIC_DOMAIN set from arguments; provider credentials left EMPTY (stub mode)."
  exit 0
fi

[ -f "$ENV_FILE" ] || die "$ENV_FILE exists but is not a regular file"
[ -r "$ENV_FILE" ] || die "$ENV_FILE is not readable"

load_existing "$ENV_FILE"

if [ "$MODE" = "check" ]; then
  # ---- CHECK (default) — the file is NOT touched at all ------------------------------------ #
  missing_list="$(missing_required || true)"
  if [ -z "$missing_list" ]; then
    note "$ENV_FILE exists and is complete — all ${#REQUIRED_KEYS[@]} prod-required keys present. No changes made."
    exit 0
  fi
  note "$ENV_FILE exists — NOT modified. Missing prod-required key(s) (names only):"
  while IFS= read -r missing_key; do
    printf '  - %s\n' "$missing_key"
  done <<<"$missing_list"
  note "fix with:  $0 --fill-missing --env-file $ENV_FILE   (mints ONLY the keys listed above)"
  exit 1
fi

# ---- FILL-MISSING --------------------------------------------------------------------------- #
# Determine what is missing BEFORE resolving, so held (non-empty) values are provably untouched.
declare -a candidates=()
for entry in "${LAYOUT[@]}"; do
  case "$entry" in
    '@'*) key="${entry#@}" ;;
    *) continue ;;
  esac
  if [ -z "${HELD[$key]+set}" ]; then candidates+=("$key"); fi
done

resolve_values

# Only keys that resolve to a NON-EMPTY value are written. A key whose canonical value is the empty
# string (optional provider credential / OAuth id) is left exactly as it is — writing `KEY=` over
# `KEY=` would be a no-op, and appending it would add noise without adding configuration.
declare -a to_fill=()
for key in ${candidates[@]+"${candidates[@]}"}; do
  if [ -n "${VAL[$key]}" ]; then to_fill+=("$key"); fi
done

if [ "${#to_fill[@]}" -eq 0 ]; then
  note "$ENV_FILE already carries every key that has a value — nothing to fill, file untouched."
  exit 0
fi

fill_into "$ENV_FILE" "${to_fill[@]}"
note "filled ${#to_fill[@]} missing key(s) in $ENV_FILE (names only): ${to_fill[*]}"
note "existing non-empty values were preserved verbatim (no secret re-minted)."
exit 0
